In [1]:
print("Basic Python Assignment")
print("Name:Raghul P.K")
print("Roll No: 310619106106")
print("1. Split this string")

Basic Python Assignment
Name:Raghul P.K
Roll No: 310619106106
1. Split this string


In [4]:
s = "Hi there Sam!"

In [5]:
strArr = s.split()
strArr


['Hi', 'there', 'Sam!']

In [39]:

print("Output should be: The diameter of Earth is 12742 kilometers.")


Output should be: The diameter of Earth is 12742 kilometers.


In [8]:
planet = "Earth"
diameter = 12742

In [9]:
print("The diameter of Earth is {} kilometers.".format(diameter))


The diameter of Earth is 12742 kilometers.


In [14]:
print("3. In this nest dictionary grab the word hello")

3. In this nest dictionary grab the word hello


In [15]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}


In [16]:
d['k1'][-1]['tricky'][-1]['target'][-1]


'hello'

In [17]:
print("Numpy")

Numpy


In [18]:
import numpy as np


In [19]:
print("4.1 Create an array of 10 zeros?")

4.1 Create an array of 10 zeros?


In [20]:
print("4.2 Create an array of 10 fives?")

4.2 Create an array of 10 fives?


In [21]:
np.zeros(10)



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10) * 5


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [23]:
print("6. Create a 3x3 matrix with values ranging from 0 to 8")

6. Create a 3x3 matrix with values ranging from 0 to 8


In [24]:
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
print("7. Concatinate a and b")


7. Concatinate a and b


In [27]:
print("a = np.array([1, 2, 3]), b = np.array([4, 5, 6])")

a = np.array([1, 2, 3]), b = np.array([4, 5, 6])


In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [29]:
print("Pandas")

Pandas


In [30]:
print("8. Create a dataframe with 3 rows and 2 columns")

8. Create a dataframe with 3 rows and 2 columns


In [31]:
import pandas as pd



In [32]:
pd.DataFrame({"Name":['ravi','ramesh','Rohith'],"RollNo":[2019115032, 2019115047, 2019115082]})


Name      RollNo
0    ravi  2019115032
1  ramesh  2019115047
2  Rohith  2019115082

In [33]:
print("9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023")


9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023


In [34]:
pd.date_range(start="2023-01-01", end="2023-02-10")


DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

In [35]:
print("10. Create 2D list to DataFrame")

10. Create 2D list to DataFrame


In [36]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]


In [37]:
pd.DataFrame(lists)


0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24